all:
  hosts:
    core:
      ansible_ssh_host: 192.168.1.137
      ansible_ssh_user: ansible
    globihost:
      ansible_ssh_host: globihost.com
      ansible_ssh_user: ansible
    ub1:
      ansible_host: 192.168.1.206    
      ansible_ssh_host: ub1.lan
      ansible_ssh_user: vagrant
    fed1:
      anisble_host: 192.168.1.207
      ansible_ssh_host: fed1.lan
      ansible_ssh_user: vagrant
  children:
    allservers:
      hosts:
#        ubuntusrv:
#        centsrv:
