all:
  hosts:
    core:
      ansible_ssh_host: 192.168.1.137
      ansible_ssh_user: ansible
    globihost:
      ansible_ssh_host: globihost.com
      ansible_ssh_user: ansible
  children:
    allservers:
      hosts:
        ubuntusrv:
        centsrv: