- name: Remove dependencies that are no longer required
  hosts: ub1
  become: yes
  gather_facts: False
  tasks:
    - name: Remove dependencies
      apt:
        autoremove: yes
        autoclean: yes